### PR TITLE
Updated links in troubleshooting doc

### PR DESCRIPTION
**Pull request by jjhegedus**
I updated broken links for the list of supported servers and proto-doc in the troubleshooting.md file.

### CODE REVIEW

**Comment by thepwagner** [comment]
This seems to break the links when rendered as HTML - https://deploy-preview-46--engine-docs.netlify.com/docs/engine/troubleshooting.html#sanity-checks

**Comment by jjhegedus** [comment]
It certainly does.  I hadn't thought of that.  Is the generation done using hexo.  I'd like to confirm a fix before I re-submit the pull request.

**Comment by thepwagner** [comment]
Yes - generation is done with Hexo.

**Comment by stubailo** [comment]
Yeah - the docs are intended to be viewed online here: https://www.apollographql.com/docs/engine/

Unfortunately it's not currently possible to have links that work in both places.

**Pull request closed without merging**
