### PR TITLE
Discussion on HTTP/2

### PR DESCRIPTION
**Pull request by johannakate**
Please continue the discussion on HTTP/2 and Engine - specifically please comment on adding the following to the documentation:

Note that we don't recommend enabling query batching with Engine for most uses. Engine supports HTTP/2 even when your server doesn't, and one of the features that allows is sending multiple requests in parallel over a single connection. In most cases, that is actually more efficient than query batching, because requests are not blocked on each other. If you want to use HTTP/2, make sure to use the sidecar in single proxy mode or deploy Engine using the Docker container.

### CODE REVIEW

**Comment by josephglanville** [comment]
This will be made better when @glasser lands his new changes that drop double proxying as a valid configuration. The final step is getting TLS support for frontends into engineproxy and then we will have a great HTTP/2 story.

**Comment by stubailo** [comment]
@glasser should we mention having HTTP2 on as a benefit of Engine in the docs or otherwise?

**Comment by stubailo** [comment]
Gonna close this for now.

**Comment by glasser** [comment]
Yes, this is now documented at https://www.apollographql.com/docs/engine/setup-node.html#https

**Pull request closed without merging**
