### PR TITLE
Fix link and typo

### PR DESCRIPTION
**Pull request by dcorb**

### CODE REVIEW

**Comment by glasser** [comment]
Good catch! Though I'm not sure that index page is actually linked from anywhere.

Fixing the typo in the URL is nice, but can you add a redirect to `public/_redirects`?

**Comment by dcorb** [comment]
Thanks
Redirection added

The index page is linked from
https://www.apollographql.com/docs/engine/
See "feature guides" link

**Comment by glasser** [comment]
There's one more in slack.md I think

**Comment by dcorb** [comment]
I think now I got them all :) Sorry for so many commits, I'm a bit lazy to checkout the repo, and Github editor forces you to commit changes file by file

**Comment by glasser** [comment]
Thanks to you! It's a little awkward for me to try to add my own changes to your branch or else I would too.

**Pull request merged**
