### PR TITLE
Updated info on apollo tracing extension in sangria

### PR DESCRIPTION
**Pull request by OlegIlyenko**

### CODE REVIEW

**Comment by glasser** [comment]
Thanks for the change (and for all your work on Sangria!)

For legal reasons we do ideally need a contributor agreement signed even for small changes like this one. Please let us know if this is prohibitive.

**Comment by OlegIlyenko** [comment]
Hey David, thanks for kind words and for looking into it. I'm not sure about CLA since it requires a full mailing address (for example, FB CLA doesn't require the mailing address for contributions from individuals). Please feel free to update the page yourself, if it's ok for you, and then just close this PR. It's just a small link update, after all, I wouldn't mind :)

**Comment by glasser** [comment]
Thanks Oleg. For this small docs change we will overlook the CLA requirement. However in general we definitely want to be in a place where major contributors to the GraphQL community like you are able to contribute to Apollo! We definitely can consider dropping the mailing address requirement if it's a hard blocker for you, though we'll have to see what the lawyers say.  We've had this CLA for about 5 years but are always up for feedback. 

A bit of research shows that the Apache Software Foundation CLA (which I personally think of as a standard for CLAs) requires mailing address.  Google does not.

**Comment by OlegIlyenko** [comment]
Thanks a lot, David! :bowing_man: I guess I just always try to stay conscious of where my private info is saved :) I'm not an expert on the subject matter either. For a bigger and more meaningful contribution, I think I would have considered signing the CLA.

**Pull request merged**
